services:
  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5174:5174'
    environment:
      VITE_API_URL: ${VITE_API_URL}
      PORT: ${PORT}
      CI: 'true'
    command: sh -c "corepack enable && CI=true pnpm install && pnpm run dev"
